### ISSUE TITLE
Unable to install `sqlalchemy==1.4.23` on Home Assistant `2022.3.3`

### ISSUE THREAD

**Issue by calexandre** [crowbarz/ha-sql_json#5]
I just updated my HA installation and all my HACS plugins to their latest version and noticed an incompatibility issue related to this plugin...

I had the following error:

```
2022-03-12 13:23:06 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package sqlalchemy==1.4.23: ERROR: Cannot install sqlalchemy==1.4.23 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

I had to uninstall this plugin, otherwise my HA would not start.

Currently running:

- HA `2022.3.3`
- Supervisor `supervisor-2022.03.3`
- Host RPI4 `Home Assistant OS 7.4`
- HACS `1.22.0`
- sql_json `1.1.0`

**Comment by crowbarz** [comment]
I bumped sqlalchemy to 1.4.27, this was updated in the upstream `sql` integration in home-assistant/core#60383 . Please try upgrading `sql_json` to 1.1.1.

**Comment by calexandre** [comment]
Its now working perfectly!
Thanks for the quick fix 👍
