### ISSUE TITLE
Unable to install `sqlalchemy==1.4.27` on Home Assistant `2022.4.7`

### ISSUE THREAD

**Issue by calexandre** [crowbarz/ha-sql_json#6]
This is an identical issue to the one reported on #5 but for a different version. I guess it will require an identical "treatment".

## Details

I just updated my HA installation and all my HACS plugins to their latest version and noticed an incompatibility issue related to this plugin...

I had the following error:

```
2022-04-25 12:24:26 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package sqlalchemy==1.4.27: ERROR: Cannot install sqlalchemy==1.4.27 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

I had to uninstall this plugin, otherwise my HA would not start.

Currently running:

- HA `2022.4.7`
- Supervisor `supervisor-2022.04.0`
- Host RPI4 `Home Assistant OS 7.4`
- HACS `1.24.5`
- sql_json `1.1.1`

**Comment by crowbarz** [comment]
I think the solution here is probably to loosen the pinning on sqlalchemy, given it is a dependency of HA core. Will look into this when I get a chance.

**Comment by crowbarz** [comment]
Try upgrading `sql_json` to [1.1.2](https://github.com/crowbarz/ha-sql_json/releases/tag/1.1.2), the `sqlalchemy` version requirement was updated to require any 1.4.* version. If this proves still to be too restrictive, then I will loosen it more (to >=1.4 I think).

Note that 2022.5.0 bumped the `sqlalchemy` requirement to 1.4.36.

**Comment by calexandre** [comment]
I confirm that the upgrade to the latest version and HA 2022.5.x are working as expected!
