### ISSUE TITLE
DB Schema changed?

### ISSUE THREAD

**Issue by galtamur** [crowbarz/ha-sql_json#7]
Hi, I am on 2022.4.7 using SQLite.
The sample query:
          SELECT CONCAT('[', GROUP_CONCAT(event_json), ']') AS json
          FROM (
            WITH events AS (
              SELECT entity_id, COUNT(*) AS event_count
              FROM (
                SELECT entity_id FROM events
                  LEFT JOIN states AS new_states ON events.event_id = new_states.event_id
                WHERE event_type = 'state_changed'
                AND time_fired BETWEEN DATE_ADD(CURDATE(), INTERVAL -1 DAY) AND CURDATE()
              ) AS entity_ids
              GROUP BY entity_id
              ORDER BY event_count DESC
            )
            SELECT JSON_OBJECT(
                'entity_id', entity_id,
                'count', event_count
            ) AS event_json
            FROM events
            LIMIT 10
          ) AS json_output

is not working, with error:
Esecuzione completata con errori.
Risultato: near "DAY": syntax error
Alla riga 1:
SELECT CONCAT('[', GROUP_CONCAT(event_json), ']') AS json
          FROM (
            WITH events AS (
              SELECT entity_id, COUNT(*) AS event_count
              FROM (
                SELECT entity_id FROM events
                  LEFT JOIN states AS new_states ON events.event_id = new_states.event_id
                WHERE event_type = 'state_changed'
                AND time_fired BETWEEN DATE_ADD(CURDATE(), INTERVAL -1 DAY

By substituting BETWEEN DATE_ADD(CURDATE(), INTERVAL -1 DAY) AND CURDATE()
with BETWEEN strftime('%Y-%m-%d', datetime('now', '-1 day', 'localtime')) AND strftime('%Y-%m-%d', datetime('now','localtime'))
I still obtain an error:
Esecuzione completata con errori.
Risultato: circular reference: events
Alla riga 1:
SELECT CONCAT('[', GROUP_CONCAT(event_json), ']') AS json
          FROM (
            WITH events AS (
              SELECT entity_id, COUNT(*) AS event_count
              FROM (
                SELECT new_states.entity_id FROM events
                  LEFT JOIN states AS new_states ON events.event_id = new_states.event_id
                WHERE event_type = 'state_changed'
                AND time_fired BETWEEN strftime('%Y-%m-%d', datetime('now', '-1 day', 'localtime')) AND strftime('%Y-%m-%d', datetime('now','localtime'))
              ) AS entity_ids
              GROUP BY entity_id
              ORDER BY event_count DESC
            )
            SELECT JSON_OBJECT(
                'entity_id', entity_id,
                'count', event_count
            ) AS event_json
            FROM events
            LIMIT 10
          ) AS json_output

Could you check? In particular, the "events" table does not appear to have an "entity_id" column nor a "event_count" columns.
The "events" table I have is containing these columns:
event_id,
event_type,
event_data,
origin,
time_fired,
created,
context_id,
context_user_id,
context_parent_id

Thank you

**Comment by crowbarz** [comment]
The example is provided as a convenience to demonstrate the integration's ability to transform the output of an SQL query into sensor attributes. I don't run an SQLlite database in my install and am not familiar with its schema and/or any recent changes to it, so am unable to assist with your query.

I would suggest asking your question in the HA community or searching for the appropriate SQL query.

As it is not functional, I will change/remove the query example to avoid any further confusion.

**Comment by crowbarz** [comment]
Fixed via 74d719affd04ed167157ee6b2cadeadf5c16eaa4
