### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by fokcuk** [crowbarz/ha-sql_json#9]
Sensor is no longer generated
`ValueError: Sensor sensor.mysql has device class None, state class None unit events and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: (<class 'str'>)`

**Comment by crowbarz** [comment]
Latest version works for me on HA 2023.5.4.

Impossible to say why it doesn't work for you from the minimal information that you provided. Can you include the version of HA and integration that you are using and your sensor configuration?

**Comment by fokcuk** [comment]
I am on 2023.5.4 as well. It worked previously but broke after the latest update (I think). I have not changed the code and SQL itself works fine.
From the logs the ValueError is all that I can see. If you can tell me where else I can check?

**Comment by fokcuk** [comment]
enabled debug logging:

`Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:583
Integration: Sensor (documentation, issues)
First occurred: 7:51:01 PM (2 occurrences)
Last logged: 7:51:01 PM

Error adding entities for domain sensor with platform sql_json
Error while setting up sql_json platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 579, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: Sensor sensor.top_water_use_events has device class None, state class None unit events and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value:  (<class 'str'>)
`

**Comment by fokcuk** [comment]
and this is my sensor:

`sensor:
  - platform: sql_json
    scan_interval: 3600 ## 1 hour
    #db_url: !secret db_url
    queries:
      - name: Top Water Use events
        query: |
          SELECT '[' || GROUP_CONCAT(event_json) || ']' AS json
          FROM (
          SELECT JSON_OBJECT('liters', CAST(state AS INT), 'datetime', datetime(last_updated_ts, 'unixepoch', 'localtime')) AS event_json
          FROM "states" 
          WHERE metadata_id=217 and CAST(state AS INT) > 20
          ORDER BY last_updated_ts DESC LIMIT 5) AS json_list;
        value_template: "{{ value_json[0].count }}"
        unit_of_measurement: events
        column: json`

**Comment by fokcuk** [comment]
think its related to https://github.com/home-assistant/core/issues/92483

**Comment by fokcuk** [comment]
and that resolved the issue. So the issue was not with the integration, with the use of "unit_of_measurement" when defining the config
